var i18n = require('i18next-text');

i18n.t = i18n.text;

module.exports = {
    logoP: i18n.t('improve your <br> english vocabulary'),
    chinese: i18n.t('Chinese'),
    arabic: i18n.t('Arabic'),
    portugal: i18n.t('Portugal'),
    russian: i18n.t('Russian'),
    spanish: i18n.t('Spanish'),
    turkish: i18n.t('Turkish'),
    signOut: i18n.t('Sign out'),
    loginVia: i18n.t('Login&nbsp;via'),
    all: i18n.t('All'),
    world: i18n.t('World'),
    politics: i18n.t('Politics'),
    economics: i18n.t('Economics'),
    tech: i18n.t('Technology'),
    sport: i18n.t('Sport'),
    science: i18n.t('Science'),
    culture: i18n.t('Culture'),
    social: i18n.t('Social'),
    tipOfTheDay: i18n.t('Click unknown word to see its translation'),
    myLang: i18n.t('My language'),
    deleteSelected: i18n.t('Delete selected'),
    cancel: i18n.t('Cancel'),
    myDictionaries: i18n.t('My dictionaries'),
    mySettings: i18n.t('My settings'),
    autosave: i18n.t('Autosave'),
    sortBy: i18n.t('Sort by'),
    az: i18n.t('A-Z'),
    timeAdded: i18n.t('Time added'),
    'Sign In': i18n.t('Sign In'),
    'Sign Up': i18n.t('Sign Up'),
    'Sign in with Facebook': i18n.t('Sign in with Facebook'),
    'Sign in with Twitter': i18n.t('Sign in with Twitter'),
    'or': i18n.t('or'),
    'Forgot password': i18n.t('Forgot password'),
    'Login': i18n.t('Login'),
    'Show my translations': i18n.t('Show my translations'),
    'Restore': i18n.t('Restore'),
    'News Sources': i18n.t('News Sources'),
    'Translations': i18n.t('Translations'),
    'Add to dictionary': i18n.t('Add to dictionary'),
    'Password': i18n.t('Password'),
    'Password again': i18n.t('Password again')
};
